title: nw.js
email: wagh.cwb@gmail.com
description: build awesome cross platforms apps with front-end technologies
welcome-message: node webkit is an app runtime based on <a href="https://www.chromium.org" target="_blank">Chromium</a> and <a href="https://nodejs.org" target="_blank">node.js</a>
baseurl: ""
url: http://nwjs.io
markdown: kramdown

github: nwjs/nw.js

gems:
  - jekyll-assets

assets:
  # cache: false
  prefix: /assets
  digest: true
  sources:
    - _assets/img
    - _assets/js
    - _assets/css
    - bower_components/
