title: nw.js
email: wagh.cwb@gmail.com
description: build awesome cross platforms apps with front-end technologies
baseurl: ""
url: http://nwjs.io
markdown: kramdown

github: nwjs/nw.js

gems:
  - jekyll-assets

assets:
  # cache: false
  prefix: /assets
  digest: true
  sources:
    - _assets/img
    - _assets/js
    - _assets/css
    - bower_components/
