title: nw.js
email: wagh.cwb@gmail.com
description: build awesome cross platforms apps with front-end technologies
welcome-message: node webkit is an app runtime based on <a href="https://www.chromium.org" target="_blank">Chromium</a> and <a href="https://nodejs.org" target="_blank">node.js</a>
baseurl: ""
url: http://0.0.0.0:4000
# url: http://nwjs.io
markdown: kramdown
destination: _deploy

github: nwjs/nw.js

gems:
  - jekyll
  - jekyll-assets
  - html-proofer
  - bootstrap-sass

exclude: ["Gemfile*", "bower.json", "README.md"]

assets:
  # cache: false
  prefix: /assets
  digest: true
  sources:
    - _assets/img
    - _assets/js
    - _assets/css
    - _assets/vendor